---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request: {}

jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.11']
    services:
      ollama:
        image: ollama/ollama
        ports: ["11434:11434"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Check formatting with Black
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run mypy
        run: mypy ml app

      - name: Run tests
        run: pytest -q

      - name: Build app image
        run: >
          docker build -f docker/app.Dockerfile
          -t rag-app:${{ github.sha }} .
