name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    services:
      ollama:
        image: ollama/ollama
        ports: ["11434:11434"]

    steps:
    - uses: actions/checkout@v4

    # —— Dependency caching ——
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # —— Static checks ——
    - run: black --check .
    - run: isort --check-only .
    - run: flake8 .
    - run: mypy ml app

    # —— Tests ——
    - run: pytest -q

    # —— Build Docker image to guarantee it still works ——
    - name: Build app image
      run: docker build -f docker/app.Dockerfile -t rag-app:${{github.sha}} .